### ISSUE TITLE
Viết dàn ý đặc tả usecase

### ISSUE THREAD

**Issue by luongminhchien1233** [NguyenHungKhang/-NguyenHungKhang-s-API-Dashboard#2]
- [x] Giới thiệu các chức năng
- [x] Viết dàn ý đặc tả:
- [x] - Hiển thị data được API trả về khi người dùng xem.
- [x] - Đăng nhập vào hệ thống nếu muốn xem dữ liệu.
- [x] - Xem và chỉnh sửa được một số thông tin của user
- [x] - Xem được thống kê liên quan tới user (từ khóa tìm kiếm được quan tâm, danh mục được xem nhiều nhất,...)
- [x] Vẽ lược đồ usecase:

**Comment by thientuyen227** [comment]
VẼ lược đồ Use Case
